### ISSUE TITLE
option for display min/max on y axis

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#124]
This should be an option rather than hard-coded one way or the other

_Originally posted by @jsoules in https://github.com/magland/spikesortingview/pull/120#discussion_r969828466_

**Comment by magland** [comment]
@jsoules while this should be an optional props parameter, I don't think we should at it to the GUI (as a toggle button) until there is a request in one of the widgets. Do you concur?

**Comment by jsoules** [comment]
I agree with that. I just don't want to lose the code, and to make sure that it can be turned on from the python if we want it.
