### ISSUE TITLE
make dragRect a function rather than redundantly tracking

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#125]
not sure it's worth it, but I'll open an issue so we can think about it.

_Originally posted by @magland in https://github.com/magland/spikesortingview/pull/117#discussion_r969831444_

**Comment by magland** [comment]
@jsoules unless you feel strongly about this one, I'm inclined to keep it the way it is because I think that's the simplest approach from usage perspective

**Comment by jsoules** [comment]
I don't feel terribly strongly about this one, it just raises the possibility of odd behavior or discrepancies between components that rely on the different fields if there should be disagreement between the stored rect and the value you would get by finding the difference between the current point and the start point.

We have plenty of other things to worry about.
