### ISSUE TITLE
Compress 1D PDF plot and remove backend dependence

### ISSUE THREAD

**Issue by edeno** [magland/spikesortingview#131]
It would be handy to be able to compare the 1D position decode with the 2D position decode. As mentioned in the meeting, the 2D decode visualization works quite well because it is highly compressed. It would be useful to do the same to the 1D position decode as well as get rid of the back end dependence to improve performance.

**Comment by jsoules** [comment]
What's the structure of the data that comes out of the 1D decoder? This is a different model from the 2D decode (right?)--what are its parameters?

Is it correct that there should be a bijective function between the 1D decoded position and the 2D decoded position, assuming the same bin counts were applied to the track in both cases?

**Comment by edeno** [comment]
The 1D decoder results will be an array of shape (n_time, n_position_bins) where as the 2D decoder results will be an array of shape (n_time, n_x_position, n_y_position). Each array value corresponds to the probability at that time and position.

For the second part, you can map from 1D to 2D position and vice versa. The binning probably won't be exactly the same due to the binning happening in 1D space in the 1D decode and 2D space in the 2D decode. I'm a little confused what you plan to do with this information though.

**Comment by edeno** [comment]
Could we also mark this one high priority as it is most immediately useful to @acomrie who has a bunch of these 1D position decodes?

**Comment by jsoules** [comment]
@edeno Well, to the extent that we can map between the 1D and 2D decoded positions, I'm thinking we could potentially display some sort of useful information about their discrepancies. I understand they're different data sets, but they're so tantalizingly similar that I want them to be all one thing...!

Thanks for confirming the format. Structurally we would just do the same trick as for the movie--convert the full sparse matrix of probability estimates into a list of probabilities, a list of buckets they correspond to, and a set of frame lengths so we can get the time code. Do you have a link for an example data file?

**Comment by edeno** [comment]
[Uploading example_1D.nc.zip…]()

**Comment by jsoules** [comment]
@edeno not sure what happened--the zipped example link you have here is (for me) just a hyperlink back to this issue page, and I'm not seeing an attachment list or anything like that...?

**Comment by edeno** [comment]
[example_1D.nc.zip](https://github.com/magland/spikesortingview/files/9575883/example_1D.nc.zip)

**Comment by jsoules** [comment]
Resolved by figurl-franklab-views PRs 5, 6, 7, 8, 11.
