### ISSUE TITLE
annotations: time intervals

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#138]
* First need a mechanism to select an interval of interest. I think shift+drag is a natural choice.
* Add that to the recording selection state.
* Make a annotation type 'time-interval'
* Display the time-interval annotations in TimeScrollView
* Click annotation to go to that interval - perhaps selected
* Figure out zooming - when clicking a time-interval annotation perhaps we want to zoom in to it.

**Comment by jsoules** [comment]
- I'd probably be more inclined to use a shift-click to create a window with the current focus as the other end; I find dragging kind of tiring if you have to do it a lot, and this might make it easier to be more precise. But either one works
- Not sure if changing the zoom level on selection is a good move--I think as a user I'd probably just want to center it, and let me control the zoom level myself if I want to zoom in... Let's ask the users

**Comment by magland** [comment]
> * I'd probably be more inclined to use a shift-click to create a window with the current focus as the other end; I find dragging kind of tiring if you have to do it a lot, and this might make it easier to be more precise. But either one works

Good point.

> * Not sure if changing the zoom level on selection is a good move--I think as a user I'd probably just want to center it, and let me control the zoom level myself if I want to zoom in... Let's ask the users

Yeah, that simplifies things if we don't try to zoom.
