### ISSUE TITLE
Use static CSS classes for constant style properties in TimeseriesView context

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#27]
There are a number of places where we add styling to components in code,
e.g. https://github.com/magland/spikesortingview/blob/2f5afe3a7bf2e551773c03f9a4ad36aeef131784/src/views/MultiTimeseries/MultiTimeseriesView.tsx#L15-L16
https://github.com/magland/spikesortingview/blob/2f5afe3a7bf2e551773c03f9a4ad36aeef131784/src/views/MultiTimeseries/ViewWrapper.tsx#L69-L76

This makes sense where the styles need to be computed, but for static styling properties it has some disadvantages compared to using CSS classes: it can lead to extra page size (especially when styled elements appear many times on the page) and it's more difficult to track down from the front-end how a particular component got a particular style property.

Suggesting we identify places where static styling is applied in code and convert them to CSS classes with semantic names, e.g. in the examples above something like `.MultiTimeseriesViewWrapperDiv`, `.MultiTimeseriesViewLabelDiv`, etc.

**Comment by magland** [comment]
I agree, this will be useful.

**Comment by jsoules** [comment]
Incidentally resolved by PR #36.
