### ISSUE TITLE
Make MultiTimeseriesView honor relative-height requests

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#29]
See src/views/MultiTimeseries/MultiTimeseriesView.tsx

We currently track the requested relative height of each panel, but we're dividing the space into N even slices for N panels regardless of the relative height parameters.

Probably need to set the total effective height as the sum of the relative heights for all panels, then adjust the allocated space for each panel according to its relative height.

The big trick here will be keeping track of how much relative height has been allocated so far--the paint method (https://github.com/magland/spikesortingview/blob/087735db9c8eaeaa38ae33839861bb51cb2b6e71/src/views/RasterPlot/TimeScrollView/paint.ts#L4-L14) currently assumes each panel has the same height and is using a vertical offset based on panel count. Instead, we'll need to make this method aware that panels can have different heights, so that it offsets by the sum of the relative-height-adjusted count of 'panel heights' already allocated.

i.e. for N panels N_1...N_n, where each panel has relative height h_i, total 'allocated height' <img src="https://render.githubusercontent.com/render/math?math=H_T=\sum_1^nh_i"/>.
https://github.com/magland/spikesortingview/blob/087735db9c8eaeaa38ae33839861bb51cb2b6e71/src/views/MultiTimeseries/MultiTimeseriesView.tsx#L19 should find the per-panel-height H_pp = height / H_t

and
https://github.com/magland/spikesortingview/blob/087735db9c8eaeaa38ae33839861bb51cb2b6e71/src/views/MultiTimeseries/MultiTimeseriesView.tsx#L24-L33
rendering each panel should use `height={panel.relativeHeight*H_pp}` so the relative height gets applied.

In https://github.com/magland/spikesortingview/blob/087735db9c8eaeaa38ae33839861bb51cb2b6e71/src/views/RasterPlot/TimeScrollView/paint.ts#L4-L14
we need to adjust the `panels` property so it tracks per-panel height, and then change the line
`context.translate(0, perPanelOffset)`
to `context.translate(0, panels[i].realizedPanelHeight)`
or something like that. (Don't recall if we optionally add a margin between panels here...)

To verify:
Example https://www.figurl.org/f?v=gs://figurl/spikesortingview-1-dev&d=601993ad3b8bc6975b8eb7c98c1c242d0276b453&channel=flatiron1&label=Jaq_03_12_visualization_data should show no difference from live version
NEW FIGURL EXAMPLE NEEDED, derived from this example, will set 'Position probability' panel to 2x height, and should show half the total drawing space allocated to the top two plots, and the other half of the drawing space allocated to the 'Position probability' plot.

**Comment by magland** [comment]
@jsoules This is actually a lot simpler than what you describe. The confusing thing is that we have multiple things called panels. Panels within a time scroll widget, and panels within a multi timeseries view. In this case it's the latter and we don't need to worry about canvas or painters or anything. Just figuring out what heights to set on the child components.

**Comment by jsoules** [comment]
Oh! The `MultiTimeseriesView` is a collection of `TimeseriesView` which are each equal-tempered (so to speak). So, right, we don't need to support this complexity, we just need to do the thing with finding an appropriate unit size for the per-panel height in MTV. Yeah, that'll be pretty straightforward.
