### ISSUE TITLE
BUG: unit selection table

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#42]
@jsoules This is a bug that was introduced with your last PR. Note that while the PR has been merged, it hasn't been deployed to the cloud yet.

https://www.figurl.org/f?v=http://localhost:3000&d=6326838558011a729862a3d8915f2f3e9210e990&channel=franklab2&label=J1620210531_.nwb_raw%20data%20valid%20times%20no%20premaze%20no%20home_24

Click on Cross-correlograms view FIRST and you will see the following incorrect display for the unit selection

![image](https://user-images.githubusercontent.com/3679296/163607148-faeb4067-ea91-4020-92dd-4bad32d88b74.png)

Whereas if you click on a different view first (like avg waveforms), then it displays correctly

![image](https://user-images.githubusercontent.com/3679296/163607222-07705941-3ded-4c61-9664-a51a6b16ea33.png)

**Comment by jsoules** [comment]
Ah, okay. Probably didn't think to put an initialization call in there for
cross-correlograms. I'll have that fixed in a sec.

**Comment by magland** [comment]
@jsoules This is a problem for some other views as well, such as spike amplitudes
See: https://www.figurl.org/f?v=http://localhost:3001&d=5153384f246686df9ef593a0fee1de7ddc350a01&channel=flatiron1&label=Test%20workspace

Ideally the initialization would not happen within the individual views... but maybe that's the way it has to be.

**Comment by jsoules** [comment]
It's actually not specific to the individual views--it's in the `SelectUnitsWidget`. Adding it there for the cross-correlograms also seems to have fixed it for spike amplitudes as well.

Agreed that we should try to minimize the number of places initialization needs to happen; hopefully the other affected views that offer selection functionality will be wrapped in an appropriate selector (like `SelectUnitsWidget`) that will mean they won't need one of their own. Please let me know if you notice any other affected views. & thanks for linking the second FigURL; I'd been looking for a place to try out how this works with the raster plot.

**Comment by jsoules** [comment]
Addressed by PR #43.
