### ISSUE TITLE
position animation control: disable text selection

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#53]
Double click on one of the controls, and text is selected. See the orange selection rect in the following screenshot:

![image](https://user-images.githubusercontent.com/3679296/167692367-870eba8b-69d4-4338-aa72-a1855c10d499.png)

I believe this can be disabled via css:
https://stackoverflow.com/questions/51712707/how-to-show-text-that-can-not-be-selected-copy-using-react

**Comment by jsoules** [comment]
Addressed in PR #54.
