### ISSUE TITLE
Mark the highest-probability position on the decoded position animation layer.

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#65]
For the decoded position animation, e.g. `TPADecodedPositionLayer.tsx` and corresponding logic.

@edeno -- a few questions to refine this.

- Are you picturing a dot like the one used for the animal position, or do you mean a special highlight for the whole track pixel?
- If it's a dot, would that go in the center of the corresponding track pixel?
- How should we resolve cases where the "highest probability" location is a tie between multiple (possibly discontinuous) track pixels?
- Do we want to suppress display of this dot if it overlaps with where the animal is? I'm thinking like, check to see if the highest-probability decoded-position identifies the track pixel that contains the observed position, or maybe some kind of radius check.

**Comment by edeno** [comment]
- Like the one used for the animal position is great.
- Center of the corresponding track pixel is perfect.
- I think in the case of ties, you can just choose the first one in the list. This is the python code I use for this: https://github.com/edeno/trajectory_analysis_tools/blob/25bdd704c7a980c643c8b9d9a27d7666bb4f77d0/trajectory_analysis_tools/posterior.py#L5-L27
- I haven't in the past bothered with suppressing the dot if it overlaps. It's an interesting idea. I think for now we can just see how the simple version looks and then add it in if it seems like it's a problem?

**Comment by magland** [comment]
I'm interested in what @edeno thinks. My first impression is that it's a bit distracting to see the green dot bouncing around so much. This could be remedied by using temporal smoothing (not for the probability map, but for determining the max bin). If that's the route @edeno wants to go, I can help out with the formula for that.

**Comment by jsoules** [comment]
If we do go that route, we should probably do so on the Python side and embed it in the data--the animation framework isn't designed to support multi-frame logic, and that might not play nicely with the ability to skip around between frames. (You could do it, but it would be kinda hacky.)

**Comment by edeno** [comment]
That looks great. My thoughts are:
+ It would be good if the color of the max probability dot pops out more.
+ I think the max probability dot could be bigger as well. We want it to stand out enough to be visually comparable to the position dot.
+ Maybe the max probability dot should go on top of the position dot.
+ Agree that the smoothing should happen on the python side if needed. I think we generally want to keep the noisiness because it could correspond to real stuff such as theta sequences when the animal is running. It is also less distracting when the animation is running at 0.125x speed.
+ I don't think the dot needs to be suppressed when it's near the animal's position
+ the speed lines/tail would be a nice feature to add.

**Comment by jsoules** [comment]
Thanks Eric.

* I can do the max probability dot whatever color you'd like--would something like rgb(79, 227, 0) be good? (My only restriction is that I'd like to avoid anything that impacts color vision issues--as is we're not doing great on that score, as the color I chose earlier is not nearly so distinct as I thought it was, and for that matter the base color scale is blending into the track a lot as well per https://www.color-blindness.com/coblis-color-blindness-simulator/... so style is definitely a WIP here!)
* I'll up the radius of the max probability dot so it matches the position dot.
* Can't easily put the max probability dot on top of the position dot because it's being drawn on the same layer as the bin probability display. If I bump that layer up above the position dot without splitting the layers, the position would be below the track shading (so you wouldn't be able to see the position at all). It might be worthwhile to split this out into another layer entirely as we add more features to it, in which case I will do it at that point--I didn't want to add another canvas layer for such a small bit of data, but maybe that's a good idea after all.
* Were there particular criteria you used for when to draw speed lines/tail on the dot?

**Comment by edeno** [comment]
> I can do the max probability dot whatever color you'd like--would something like rgb(79, 227, 0) be good? (My only restriction is that I'd like to avoid anything that impacts color vision issues--as is we're not doing great on that score, as the color I chose earlier is not nearly so distinct as I thought it was, and for that matter the base color scale is blending into the track a lot as well per https://www.color-blindness.com/coblis-color-blindness-simulator/... so style is definitely a WIP here!)

I think that will work

> I'll up the radius of the max probability dot so it matches the position dot.

👍 

> Can't easily put the max probability dot on top of the position dot because it's being drawn on the same layer as the bin probability display. If I bump that layer up above the position dot without splitting the layers, the position would be below the track shading (so you wouldn't be able to see the position at all). It might be worthwhile to split this out into another layer entirely as we add more features to it, in which case I will do it at that point--I didn't want to add another canvas layer for such a small bit of data, but maybe that's a good idea after all.

Okay, let's just leave it where it is for now. This is not so important.

> Were there particular criteria you used for when to draw speed lines/tail on the dot?

I used the last five time bins for max probability dot to draw the tail.

**Comment by jsoules** [comment]
> I used the last five time bins for max probability dot to draw the tail.

I'm not sure I follow. Do you connect all 5 of them with a line/trail, or are they just dots? Should they be decreasing in size as they get farther back in time? (I can also just play around with it if you like.)

**Comment by edeno** [comment]
Yes--connected with a line. It is only a line.
