### ISSUE TITLE
Improve styling for color-blindness issues

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#77]
See https://www.color-blindness.com/coblis-color-blindness-simulator/

I'm particularly concerned with the decoded probability animation, but we should look at other visualizations as well to make sure they degrade gracefully for people with different levels of color vision.

**Comment by magland** [comment]
There's a related issue on sortingview https://github.com/magland/sortingview/issues/186
Waiting to here back from Loren and Eric on that. Marking this one as low priority for now.

**Comment by jsoules** [comment]
This should be largely resolved by the updates to color templates/color scale choices coming out of figurl-franklab-views PR #12 (https://github.com/magland/figurl-franklab-views/pull/12)
