### ISSUE TITLE
y-axis ticks: address scaling issues during scrolling?

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#89]
e.g. https://www.figurl.org/f?v=gs://figurl/spikesortingview-8&d=sha1://056c59aae3f29f48426be38516a6e84496985edf&label=Position%20plot%20example&s={}

If we zoom in and pan through the data series, the range of values in the visible window changes. This causes the y-axis scale to change (and the ticks to change correspondingly) in real time.

On the one hand, this may be intended behavior, since the scale and tick marks are supposed to change to accommodate the available data. On the other hand, it might be nice to keep the y-axis scale consistent during a pan operation (although this will impose awkward linkages between panning state and the overall component layout/dimensions).

Think about whether we want to do anything here.

**Comment by magland** [comment]
position plot is being replaced by TimeseriesGraph, which doesn't have this property, so I am closing this issue.
