### ISSUE TITLE
y-axis ticks: inappropriate values displayed for some data series

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#91]
https://www.figurl.org/f?v=gs://figurl/spikesortingview-8&d=sha1://c9ae9a07468d6f55cf5b6713bb068554247e749d&label=test_spike_amplitudes&s={}

Select units 0 and 6, zoom in (via wheel) a few times on 1 min 20 s. Note that some minor y-axis ticks are displaying incorrectly as large 0-prefixed numbers, e.g. `000001` instead of `0.6`. Suspect a rounding error or similar--investigate this.

**Comment by magland** [comment]
@jsoules I can't reproduce this. Could you provide a screenshot?

**Comment by magland** [comment]
Oh nvm @jsoules , I was looking at the wrong axis.

**Comment by magland** [comment]
Fixed this by doing precision rounding in a couple places
```javascript
Math.round(x * 1e9) / 1e9
```
